# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\quocs\Desktop\design.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.img_person = QtWidgets.QGraphicsView(self.centralwidget)
        self.img_person.setGeometry(QtCore.QRect(550, 30, 261, 221))
        self.img_person.setObjectName("img_person")
        self.txt_name = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_name.setGeometry(QtCore.QRect(190, 40, 291, 41))
        self.txt_name.setObjectName("txt_name")
        self.txt_mssv = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_mssv.setGeometry(QtCore.QRect(190, 90, 291, 41))
        self.txt_mssv.setObjectName("txt_mssv")
        self.txt_khoa = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_khoa.setGeometry(QtCore.QRect(190, 150, 291, 41))
        self.txt_khoa.setObjectName("txt_khoa")
        self.txt_computer = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_computer.setGeometry(QtCore.QRect(190, 210, 291, 41))
        self.txt_computer.setObjectName("txt_computer")
        self.txt_uuid = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_uuid.setGeometry(QtCore.QRect(190, 390, 291, 41))
        self.txt_uuid.setObjectName("txt_uuid")
        self.txt_memory = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_memory.setGeometry(QtCore.QRect(190, 460, 291, 41))
        self.txt_memory.setObjectName("txt_memory")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(30, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.mssv = QtWidgets.QLabel(self.centralwidget)
        self.mssv.setGeometry(QtCore.QRect(30, 90, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mssv.setFont(font)
        self.mssv.setObjectName("mssv")
        self.khoa = QtWidgets.QLabel(self.centralwidget)
        self.khoa.setGeometry(QtCore.QRect(30, 150, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.khoa.setFont(font)
        self.khoa.setObjectName("khoa")
        self.computer = QtWidgets.QLabel(self.centralwidget)
        self.computer.setGeometry(QtCore.QRect(30, 210, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.computer.setFont(font)
        self.computer.setObjectName("computer")
        self.uuid = QtWidgets.QLabel(self.centralwidget)
        self.uuid.setGeometry(QtCore.QRect(30, 390, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.uuid.setFont(font)
        self.uuid.setObjectName("uuid")
        self.memory = QtWidgets.QLabel(self.centralwidget)
        self.memory.setGeometry(QtCore.QRect(30, 460, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.memory.setFont(font)
        self.memory.setObjectName("memory")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # self.txt_memory.setDisabled(True)
        # self.txt_uuid.setDisabled(True)
        # self.txt_computer.setDisabled(True)
        # self.txt_khoa.setDisabled(True)
        # self.txt_mssv.setDisabled(True)
        # self.txt_name.setDisabled(True)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "Name"))
        self.mssv.setText(_translate("MainWindow", "MSSV"))
        self.khoa.setText(_translate("MainWindow", "Khoa"))
        self.computer.setText(_translate("MainWindow", "Computer"))
        self.uuid.setText(_translate("MainWindow", "UUID"))
        self.memory.setText(_translate("MainWindow", "Memory"))

